@echo off
echo Starting API in background...
start /B python -m uvicorn src.api:app --host 127.0.0.1 --port 8000
timeout /t 15
echo Running tests...
python tests/test_api.py
echo Stopping API...
taskkill /F /IM python.exe
