import os
from datetime import datetime

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_html_report(self, alerts: list, actions: list) -> str:
        """
        Generates a summary HTML report.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        filename = f"SIEM_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(self.output_dir, filename)

        html_content = f"""
        <html>
        <head>
            <title>AI-NIDS Security Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                h1 {{ color: #2E4053; }}
                h2 {{ color: #2874A6; border-bottom: 2px solid #ddd; padding-bottom: 10px; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                th {{ background-color: #F2F3F4; }}
                .alert-high {{ color: #C0392B; font-weight: bold; }}
            </style>
        </head>
        <body>
            <h1>🛡️ AI-NIDS Security Report</h1>
            <p><strong>Generated on:</strong> {timestamp}</p>
            
            <h2>🚨 High Priority Alerts</h2>
            <table>
                <tr>
                    <th>Severity</th>
                    <th>Alert Name</th>
                    <th>Source IP</th>
                    <th>Time</th>
                </tr>
        """
        
        for alert in alerts:
            html_content += f"""
                <tr>
                    <td class="alert-high">{alert.get('severity', 'Unknown')}</td>
                    <td>{alert.get('name', 'N/A')}</td>
                    <td>{alert.get('source_ip', 'N/A')}</td>
                    <td>{alert.get('timestamp', 'N/A')}</td>
                </tr>
            """
            
        html_content += """
            </table>
            
            <h2>🤖 Automated Response Actions</h2>
            <table>
                <tr>
                    <th>Action</th>
                    <th>Target</th>
                    <th>Status</th>
                    <th>Executor</th>
                </tr>
        """
        
        for action in actions:
            html_content += f"""
                <tr>
                    <td>{action.get('action', 'N/A')}</td>
                    <td>{action.get('target', 'N/A')}</td>
                    <td>{action.get('status', 'N/A')}</td>
                    <td>{action.get('executor', 'System')}</td>
                </tr>
            """
            
        html_content += """
            </table>
            <br>
            <p><em>Generated by AI-NIDS GenAI Analyst</em></p>
        </body>
        </html>
        """
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        return filepath
